version: "1.0"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - tmp:/usr/share/nginx/html:ro # Test volume 1
      - tmp2:/usr/share/nginx:ro # Test volume 2
    ports:
      - "8081:80" # Test port 1
      - "8082:80" # Test port 2
    environment:
      - NGINX_HOST=foobar.com # Test environment 1
      - NGINX_PORT=80 # Test environment 2
  mariadb:
    image: mariadb:latest
    restart: always # TODO
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example