version: "1.0"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - tmp:/usr/share/nginx/html:ro # Test volume 1
      - tmp2:/usr/share/nginx:ro # Test volume 2
    ports:
      - "8081:80" # Test port 1
      - "8082:80" # Test port 2
    environment:
      - NGINX_HOST=foobar.com # Test environment 1
      - NGINX_PORT=80 # Test environment 2
      - TEST1={TEST1} # Test1 environment from .env file
      - TEST2={TEST2} # Test2 environment from .env file
  mariadb:
    image: mariadb:latest
    restart: always # TODO
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=example
#  error1:
#    image: no-image
#  error2:
#    image: nginx:alpine
#    volumes:
#      - tmp:no-path:ro