name: go-continues-deployment

on:
  workflow_run:
    workflows: ['go-continues-integration-and-delivery']
    types:
      - completed
      
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test Go binaries
      run: cd src && go test .
