name: go-continuous-deployment

on:
  workflow_run:
    workflows: ['go-continuous-integration-and-delivery']
    types:
      - completed
      
jobs:

  test1:
    name: Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore cached Go binaries
        uses: actions/cache@v2
        id: restore-build
        with:
          path: src/bin
          key: podman-compose-cache-key
      - run: ls
