name: go-continuous-deployment

on:
  workflow_run:
    workflows: ['go-continuous-integration-and-delivery']
    types:
      - completed
      
jobs:
  
  download:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Download
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: releasement.yml
          workflow_conclusion: success
          name: artifact-podman-compose

      - name: Cache Go binaries
        uses: actions/cache@v2
        id: restore-build
        with:
            path: .
            key: podman-compose-cache-key

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [download]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore cached Go binaries
        uses: actions/cache@v2
        id: restore-build
        with:
          path: .
          key: podman-compose-cache-key
