name: go-continuous-deployment

on:
  workflow_run:
    workflows: ['go-continuous-integration-and-delivery']
    types:
      - completed
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  VERSION: v1.0.4
    
jobs:
  
  download:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Download
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Download artifact - Darwin (ARM64)
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: releasement.yml
          workflow_conclusion: success
          name: artifact-darwin-arm64
          path: bin/darwin/arm64
      - run: ls bin/darwin/arm64

      - name: Download artifact - Darwin (AMD64)
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: releasement.yml
          workflow_conclusion: success
          name: artifact-darwin-amd64
          path: bin/darwin/amd64
      - run: ls bin/darwin/amd64

      - name: Download artifact - Linux (AMD64)
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: releasement.yml
          workflow_conclusion: success
          name: artifact-linux-amd64
          path: bin/linux/amd64
      - run: ls bin/linux/amd64

      - name: Cache Go binaries
        uses: actions/cache@v2
        id: restore-build
        with:
            path: bin
            key: ${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [download]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore cached Go binaries
        uses: actions/cache@v2
        id: restore-build
        with:
          path: bin
          key: ${{ github.sha }}
      - run: |
          ls bin/darwin/arm64
          ls bin/darwin/amd64
          ls bin/linux/amd64

      - name: Zip Go binaries
        run: |
          cd bin/darwin/arm64
          zip podman-compose-darwin-arm64.zip *
          cd ../amd64
          zip podman-compose-darwin-amd64.zip *
          cd ../../linux/amd64
          zip podman-compose-linux-amd64.zip *
          ls

      - name: Remove old release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true # default: false
          tag_name: ${{ env.VERSION }} # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          #tag_name: ${{ github.ref }}
          #release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release asset - MacOS (ARM64)
        id: upload-release-asset-macos-arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/darwin/arm64/podman-compose-darwin-arm64.zip
          asset_name: podman-compose-darwin-arm64.zip
          asset_content_type: application/zip
          
      - name: Upload release asset - MacOS (AMD64)
        id: upload-release-asset-macos-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/darwin/amd64/podman-compose-darwin-amd64.zip
          asset_name: podman-compose-darwin-amd64.zip
          asset_content_type: application/zip

      - name: Upload release asset - Linux (AMD64)
        id: upload-release-asset-linux-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/linux/amd64/podman-compose-linux-amd64.zip
          asset_name: podman-compose-linux-amd64.zip
          asset_content_type: application/zip    
