name: go-continues-integration-and-delivery

on:
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: cd src && go build -v . && ls

    - name: Test
      run: cd src && go test -v .
  
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Upload a Build Artifact
    - uses: actions/upload-artifact@v2
      with:
        name: podman-compose
        path: podman-compose
