name: go-continuous-integration-and-delivery

on:
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]
    paths:
      - '**.go'

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test Go application
      run: go test .

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Go binary for MacOS (ARM64)
      run: env GOOS=darwin GOARCH=arm64 go build -o bin/darwin/arm64/podman-compose

    - name: Build Go binary for MacOS (AMD64)
      run: env GOOS=darwin GOARCH=amd64 go build -o bin/darwin/amd64/podman-compose
      
    - name: Build Go binary for Linux (AMD64)
      run: env GOOS=linux GOARCH=amd64 go build -o bin/linux/amd64/podman-compose

    - name: Cache Go binaries
      uses: actions/cache@v2
      id: restore-build
      with:
          path: bin
          key: ${{ github.sha }}

  upload:
    name: Upload
    runs-on: ubuntu-latest
    needs: [test, build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore cached Go binaries
        uses: actions/cache@v2
        id: restore-build
        with:
          path: bin
          key: ${{ github.sha }}

      - name: Create artifact for MacOS (ARM64)
        uses: actions/upload-artifact@v2
        with:
          name: artifact-darwin-arm64
          path: bin/darwin/arm64/

      - name: Create artifact for MacOS (AMD64)
        uses: actions/upload-artifact@v2
        with:
          name: artifact-darwin-amd64
          path: bin/darwin/amd64/

      - name: Create artifact for Linux (AMD64)
        uses: actions/upload-artifact@v2
        with:
          name: artifact-linux-amd64
          path: bin/linux/amd64/
