name: go-continuous-integration-and-delivery

on:
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test Go application
      run: cd src && go test .

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Go binary for MacOS (Arm64)
      run: cd src && env GOOS=darwin GOARCH=arm64 go build -o bin/podman-compose-macos_arm64

    - name: Build Go binary for MacOS (Amd64)
      run: cd src && env GOOS=darwin GOARCH=amd64 go build -o bin/podman-compose-macos_amd64
      
    - name: Build Go binary for Linux (Amd64)
      run: cd src && env GOOS=linux GOARCH=amd64 go build -o bin/podman-compose-linux_amd64 && ls src/bin

    - name: Cache Go binaries
      uses: actions/cache@v2
      id: restore-build
      with:
          path: src/bin
          key: ${{ github.sha }}

  upload:
    name: Upload
    runs-on: ubuntu-latest
    needs: [test, build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore cached Go binaries
        uses: actions/cache@v2
        id: restore-build
        with:
          path: src/bin
          key: ${{ github.sha }}

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact-podman-compose
          path: src/bin
