name: go-continues-integration-and-delivery

on:
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test Go binaries
      run: cd src && go test .

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Go binaries
      run: cd src && go build -v .

    - name: Cache Go binaries
      run: ls
    - uses: actions/cache@v2
      id: restore-build
      with:
          path: ./*
          key: ${{ github.sha }}
